<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>McMotd.Net.Razor</PackageId>
    <Version>0.1.0</Version>
    <Authors>NJoyShadow</Authors>
    <Copyright>Copyright (c) NJoyShadow 2023</Copyright>
    <PackageProjectUrl>https://github.com/N-Joy-Shadow/McMotd.Net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/N-Joy-Shadow/McMotd.Net/tree/stable/McMotdParser.Razor</RepositoryUrl>
    <RepositoryType>github</RepositoryType>
    <PackageTags>minecraft,minecraft-motd,motd,razor</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Description>
      McMotd.Net for Razor Component
    </Description>
    <RootNamespace>McMotdParser.Razor</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="7.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\McMotd\McMotd.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
