<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>McMotd.Net</PackageId>
    <Authors>NJoyShadow</Authors>
    <PackageVersion>0.1.0</PackageVersion>
    <Copyright>Copyright (c) NJoyShadow 2023</Copyright>
    <PackageProjectUrl>https://github.com/N-Joy-Shadow/McMotd.Net</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageTags>minecraft,motd,minecraft-motd</PackageTags>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>
      McMotd can parse Raw minecraft motd to Html as string
    </Description>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/N-Joy-Shadow/McMotd.Net/tree/stable/McMotdParser</RepositoryUrl>
    <RepositoryType>github</RepositoryType>
    <RootNamespace>McMotdParser</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\"/>
    <None Include="../LICENSE.txt" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
